language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "JR8aD/i8CoXjUyH6njPOigWAoyf5tDHF+t6gA4MSxlAFma7HVx3ZuWJD17U9ov7aMVcf8TKgrzyyIWL6PB6sysVSv0A73SKzQL2NQmbuovDigdHjx5aY+wkEyki5w3zFTUDUDLOfeWnJKINJrKhQ+0qjh3nnl60YvY6O6AU368xoZ6laLaIslTPya60UUOO0tRJrED7sJ8Ic8UxJFzRh/Dlk/wrdR+UmBwOPFpJTHkhfe8NSV5z4kE0tqff04BXsz0pUgdjFn3DHwf9AZPOrzAh91DyI14GpOPGlESr0epXjpFBy2bWXIzORhq0D0aDswfDF2NJmRWVMxocLydIBVEV3QNyNEZyeYrwXcdo3eZgiR+CUVQ/rDe0y7dMCnU+OQkRgPTiRBgqqTc2H/DH/AsBpbvDnNG2tJ8QEOniC2J7Fqg6pzTryTixLPijli58bLfRPKNkwS51BliTvyQMN+NArBvS4sYQJNHni5rcInIjnVO6eUjQiSTHi9cUcqAdLPOeiQCo/kXdlni4Id/cOg65YikOG8vnZfIsLsowxagXppjbt5/+7Lh797LUtZWKmmvTFEs59Li9/SbOS/61MaiWzJv2DhtCV/EDypwOtJL85/aKEcMHTq7cH0v2FfHnH4V6UkNqni9zS+1/0uGW33fp+mpzCf6YddiqiL+XeeGA="
  app: expediaassignment
